config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :image_comments
  root 'static_pages#home'
  get 'user' => 'users#index'


  devise_for :users

  resources :users do
    member do
      get :following, :followers
      get :live_search
    end
  end

get '/users/searches', to: 'searches#index'
  
resources :relationships,       only: [:create, :destroy]
get '/user/:id' => 'users#show'
  resources :images do
    resource :like
  end
  get '/user/:id' => 'users#show', as: 'showuser'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @image.likes.where(user_id: current_user.id).first_or_create
    respond_to do |format|
      format.html { redirect_to @image }
      format.js
    end
  end

  def destroy
    @image.likes.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html { redirect_to @image }
      format.js
    end
  end

  private

  def set_post
    @image = Image.find(params[:image_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_likes.html.erb
<% if user_signed_in? && current_user.likes?(post) %>
    <%= link_to image_like_path(post), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-thumbs-down"></span> Unlike
    <% end %>
<% else %>
    <%= link_to image_like_path(post), method: :post, remote: true do %>
        <span class="glyphicon glyphicon-thumbs-up"></span> Like
    <% end %>
<% end %>
<%= post.likes.count %>

app/views/likes/create.js.erb
$("#post_<%= @image.id %>_likes").html("<%=j render partial: "likes", locals: {post: @image} %>");

app/views/likes/destroy.js.erb
$("#post_<%= @image.id %>_likes").html("<%=j render partial: "likes", locals: {post: @image} %>");