config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :image_comments
  root 'static_pages#home'
  get 'user' => 'users#index'


  devise_for :users

  resources :users do
    member do
      get :following, :followers
      get :live_search
    end
  end

get '/users/searches', to: 'searches#index'
  
resources :relationships,       only: [:create, :destroy]
get '/user/:id' => 'users#show'
  resources :images do
    resource :like
  end
  get '/user/:id' => 'users#show', as: 'showuser'
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = User.where("lower(email) LIKE ?", '%' + params[:email].downcase + '%').paginate(page: params[:page], per_page: 10).order(:id)
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.fetch(:search, {})
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<div class="container">
    <div class="row col-md-6 col-md-offset-2 custyle">
        <table class="table table-hover custab">
            <thead>
                <tr>
                    <th>Email</th>
                    
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <% @searches.each do |user| %>
            <tr>
                <td><%= link_to(user.email, showuser_path(user)) %></td>
                
                <td class="text-center">
                  <% if user_signed_in? %>
                  <% if current_user != user %>
                                              <div id="follow_form">
                                                <% if current_user.following?(user) %>
                                                <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
                                                                         html: { method: :delete },
                                                                         remote: true) do |f| %>
                                                              <%= f.submit "Unfollow", class: "btn" %>
                                                            <% end %>
                                                <% else %>
                                                <%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
                                                          <div><%= hidden_field_tag :followed_id, user.id %></div>
                                                          <%= f.submit "Follow", class: "btn btn-primary" %>
                                                        <% end %>
                                                <% end %>
                                              </div>
                                              <% end %>
                                              <% end %>
                </td>
            </tr>
         <% end %> 
        </table>
    </div>
</div>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>