config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :image_comments
  root 'static_pages#home'
  get 'user' => 'users#index'


  devise_for :users

  resources :users do
    member do
      get :following, :followers
      get :live_search
    end
  end

get '/users/searches', to: 'searches#index'
  
resources :relationships,       only: [:create, :destroy]
get '/user/:id' => 'users#show'
  resources :images do
    resource :like
  end
  get '/user/:id' => 'users#show', as: 'showuser'
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :file, ImageUploader
    belongs_to :user
    belongs_to :category
    has_many :image_comment, -> { order "created_at DESC"}
    has_many :likes
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image_comment = ImageComment.new
  end

  # GET /images/new
  def new
    @image = Image.new
    @category_options = Category.all.map{ |u| [ u.name, u.id ] }
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id
    @image.category_id = params[:category_id]
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:user_id, :title, :file, :created_at, :category_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image, {multipart: true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %> <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Image' %><br>
    <%= f.file_field :file %>
  </div>
  
  <!-- <div> -->
    <%#= f.label 'Category' %><br>
    <%#= select_tag 'category_id', options_for_select(@category_options) %>
  <!-- </div> -->
  <div class="actions">
    <%= f.submit class: "btn btn-default"%>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<br>
<%#= link_to 'Show', @image, class: "btn btn-default" %>
<%= link_to 'Back', @image, class: "btn btn-default" %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>File</th>
      <th>Created at</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.user_id %></td>
        <td><%= image.title %></td>
        <td><%= image.file %></td>
        <td><%= image.created_at %></td>
        <td><%= image.category_id %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<div class="row">
    <div class="col-md-6">
        <div class="information-form">
            <h3>Upload an image</h3>
			<%= render 'form' %>
			<br>
			<%= link_to "Back", :back , class: "btn btn-default" %>
		</div>
	</div>
</div>

app/views/images/show.html.erb
<div class="image-show row">
  <div class="col-md-6">
    <%= image_tag @image.file, class: "img-responsive"%>
  </div>
  <div class="col-md-6">
    <p>
      <strong><%= link_to @image.user.email, :controller => "users", :action => "show", :id => current_user.id %></strong> at  <strong><%= @image.created_at %> </strong>   
    </p>
    <h3>
      <%= @image.title %>
    </h3>
    <div class="new-comment">
      <!-- <h2>コメントフォーム</h2> -->
      <%= form_for(@image_comment) do |f| %>
      <div class= "field">
        <%#= f.label :comment %><br>
        <%= f.text_field :comment , placeholder: 'Comment here...', class: "comment"%>
        <%= f.hidden_field :image_id, :value => @image.id %>
        <%= f.submit 'Comment' , class: "btn btn-default"%>
      </div>
      <% end %>
    </div>
    <br>
    <% if @image.image_comment %>
    <div class = "image-comment">
      <!-- <h2>コメント一覧</h2> -->
      <ul>
        <% @image.image_comment.each do |image_comment|%>
        <li>
          <% if image_comment.user %><strong><%= link_to image_comment.user.email, :controller => "users", :action => "show", :id => image_comment.user.id %></strong>
          <% else %>
            <strong>Unknown User</strong>
          <% end %>
          <%= image_comment.comment %>
        </li>
        <% end %>
      </ul>
    </div>
    <div>
      <div id="post_<%= @image.id %>_likes">
        <%= render "likes/likes", post: @image %>
      </div>
    </div>
    <br>
    <% end %>
    <%#= link_to 'Back', {:controller => "users", :action => "show", :id => @image.user.id}, class: "btn btn-default"%>
    <%= link_to "Back", :back , class: "btn btn-default" %>
    <% if current_user.id == @image.user.id %>
    <%= link_to 'Edit', edit_image_path(@image) , class: "btn btn-default" %>
    <% end %>
  </div>
</div>